In [3]:
#eval() accepts both int and float type data

a=eval(input("Enter a: "))
b=eval(input("Enter b: "))
print(a+b)



Enter a: 4
Enter b: 34
38


In [11]:
a="abcde"
b="dbbfvdf"
name=a.capitalize()+" "+b.capitalize()
name



'Abcde Dbbfvdf'

## Reverse string

In [8]:
a="abcde"
a[::-1]

'edcba'

## splitting string by space

In [9]:
str1="ABC DEF GHI"
str1.split()

['ABC', 'DEF', 'GHI']

In [10]:
str1="ABC-DEF-GHI"
str1.split("-")

['ABC', 'DEF', 'GHI']

## Counting characters

In [18]:
name="anknnnjjbnohi"
vow="aeiouAEIOU"
count=0
for i in name:
    if i in vow:
        count+=1
print(count)        

3


In [19]:
str2="acbd"
newstr=""
for i in str2:
    if i=="c":
        newstr+="X"
    else:
        newstr+=i
print(newstr)        

aXbd


# write a program to replace all the vowels in a following string

In [20]:
name="accgdhdipd"
vow="aeiouAEIOU"
newstr=""
for i in name:
    if i in vow:
        newstr+="X"
    else:
        newstr+=i  
print(newstr)     

XccgdhdXpd


# Some important methods of string

In [21]:
str1="abcde"
str1.upper()

'ABCDE'

In [22]:
str1.lower()

'abcde'

In [24]:
str1="abcd1234##$$"
print(str1.isdigit())
print(str1.isalnum())
print(str1.isalpha())

False
False
False


# How to check it contains special characters 

In [39]:
str1="abcd1234"
if str1.isalnum()==False:
    print("str1 contains special characters")
else:
    print("str1 not contains special characters")

str1 not contains special characters


## Introduction to list

In [28]:
lst=[1,2,3,4,"abc","def"]
print(lst)

[1, 2, 3, 4, 'abc', 'def']


In [29]:
print(*lst)

1 2 3 4 abc def


In [30]:
print(*lst,sep="\n")

1
2
3
4
abc
def


In [34]:
lst3=[1,2,4,6,2,3,0,6,3]
lst3.sort(reverse=True)
lst3
print(sum(lst3)/len(lst3))

3.0


# find the median of lst3

In [41]:
import math
lst3=[1,6,3,7,9,6,3,2]
lst3.sort()
print(lst3)
if len(lst3)%2!=0:
    mid=len(lst3)/2
    medn=lst3[mid]
elif len(lst3)%2==0:
    mid1=math.floor(len(lst3)/2)-1
    mid2=math.ceil(len(lst3)/2)
    medn=(lst3[mid1]+lst3[mid2])/2
print("Median of the list is: ",medn)    

[1, 2, 3, 3, 6, 6, 7, 9]
Median of the list is:  4.5


# Important method in list

In [44]:
lst=[1,2,3,4,5]
lst.append(20)
lst

[1, 2, 3, 4, 5, 20]

In [45]:
lst.insert(0,100) ## (index,value)
lst

[100, 1, 2, 3, 4, 5, 20]

In [59]:
lst1=[1,2,3,4]
lst2=[5,6,7,8]
print(lst1+lst2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [60]:
lst1.extend(lst2)
lst1

[1, 2, 3, 4, 5, 6, 7, 8]

In [50]:
lst1.remove(3)
lst1

[1, 2, 4, 5, 6, 7, 8, 5, 6, 7, 8]

In [51]:
lst1.pop()

8

In [65]:
lst1.pop(-1)

7

In [62]:
lst1.count(3)

1

In [63]:
lst1.index(3)

2

# Introduction to Dictonary 


### dict={"key":"value"}

In [71]:
dict1={}
dict1["name"]=["ABC","DEF","GHI"]
print(dict1)
dict1["dict2"]={"num":"123"}
print(dict1)

{'name': ['ABC', 'DEF', 'GHI']}
{'name': ['ABC', 'DEF', 'GHI'], 'dict2': {'num': '123'}}


In [75]:
d1={"A":100,"B":200}
d2={"A":300,"C":400}
print("Before Update")
print(d1)
print("After Update")
d1.update(d2)
print(d1)

Before Update
{'A': 100, 'B': 200}
After Update
{'A': 300, 'B': 200, 'C': 400}


# Write a program to insert the details of 4 student by the following key details:


1.Name: ["ABC","DEF"]


2.Roll:[23,45]


3.stream:["CSE","ECE"]



4.Marks:[45,43]

In [78]:
n=[];r=[];s=[];m=[]
for i in range(4):
    print("\n")
    n.append(input("Enter your name : "))
    r.append(input("Enter your roll no : "))
    s.append(input("Enter your stream : "))
    m.append(eval(input("Enter your mark : ")))
student={}    
student["Name"]=n
student["Roll"]=r
student["Stream"]=s
student["Marks"]=m
print(student)




Enter your name : subhram
Enter your roll no : 23
Enter your stream : CSE
Enter your mark : 564


Enter your name : raj
Enter your roll no : 43
Enter your stream : CSE
Enter your mark : 76


Enter your name : Rahul
Enter your roll no : 65
Enter your stream : EEE
Enter your mark : 65


Enter your name : Manas
Enter your roll no : 54
Enter your stream : ECE
Enter your mark : 64
{'Name': ['subhram', 'raj', 'Rahul', 'Manas'], 'Roll': ['23', '43', '65', '54'], 'Stream': ['CSE', 'CSE', 'EEE', 'ECE'], 'Marks': [564, 76, 65, 64]}


In [81]:
dct={"Name":[],"Roll":[],"Stream":[],"Marks":[]}
for i in range(4):
    dct.get("Name").append(input("Enter your name : "))
    dct.get("Roll").append(input("Enter your roll no : "))    
    dct.get("Stream").append(input("Enter your stream : "))    
    dct.get("Marks").append(eval(input("Enter your mark : ")))    

Enter your name : subhram
Enter your roll no : 23
Enter your stream : cse
Enter your mark : 34
Enter your name : abhishek
Enter your roll no : 45
Enter your stream : cse
Enter your mark : 33
Enter your name : sourav
Enter your roll no : 45
Enter your stream : eee
Enter your mark : 445
Enter your name : raj
Enter your roll no : 65
Enter your stream : eee
Enter your mark : 23


In [84]:
dct

{'Name': ['subhram', 'abhishek', 'sourav', 'raj'],
 'Roll': ['23', '45', '45', '65'],
 'Stream': ['cse', 'cse', 'eee', 'eee'],
 'Marks': [34, 33, 445, 23]}

# Introduction to array

In [85]:
import numpy as np

In [88]:
lst=[1,2,3,4,5]
arr=np.array(lst)
print(arr)

[1 2 3 4 5]


In [90]:
lst1=[1,3,2.3,23,"abc"]
print(np.array(lst1))

['1' '3' '2.3' '23' 'abc']


In [100]:
lst2=[[1,2,7],[4,5,6],[7,8,9]]
arr=np.array(lst2)
arr

array([[1, 2, 7],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
print(np.diagonal(arr[::-1]))
sum(np.diagonal(arr[::-1]))

[7 5 7]


19

In [114]:
sum(np.flip(arr,axis=1).diagonal())

19