## Importing numpy

In [2]:
import numpy as np

In [3]:
l1=[1,2,3,4,5,6,7,8,9]
l2=[[1,2,3],[4,5,6],[7,8,9]]

## converting list to an numpy array

In [4]:
arr1=np.array(l1)
arr2=np.array(l2)
print(arr1)
print(arr2)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Data type of array

In [6]:
print("Data type of arr1 : ",arr1.dtype)
print("Data type of arr2 : ",arr2.dtype)

Data type of arr1 :  int32
Data type of arr2 :  int32


## Type of array

In [7]:
print("type of arr1 : ",type(arr1))
print("type of arr2 : ",type(arr2))

type of arr1 :  <class 'numpy.ndarray'>
type of arr2 :  <class 'numpy.ndarray'>


## size of array

In [9]:
print("size  of arr1 : ",arr1.size)
print("size  of arr2 : ",arr2.size)

size  of arr1 :  9
size  of arr2 :  9


## length of array

In [10]:
print("length of arr1 : ",len(arr1))
print("length of arr2 : ",len(arr2))

length of arr1 :  9
length of arr2 :  3


## Memory space allocation of a array

In [16]:
print("Item size of array arr1:",arr1.itemsize)
print("Memory space allocation of arr1:",arr1.size*arr1.itemsize)
print("Memory space allocation of arr1:",arr1.nbytes)

Item size of array arr1: 4
Memory space allocation of arr1: 36
Memory space allocation of arr1: 36


## Dimension of an array

In [18]:
print("Dimension of an array arr1",arr1.ndim)
print("Dimension of an array arr2",arr2.ndim)

Dimension of an array arr1 1
Dimension of an array arr2 2


## cumulative product

In [19]:
print("cumulative product of arr1",np.cumprod(arr1))

cumulative product of arr1 [     1      2      6     24    120    720   5040  40320 362880]


l1=[1,2,3,4,5,6,7,8,9]


## cumulative sum

In [20]:
print("cumulative sum of arr1",np.cumsum(arr1))

cumulative sum of arr1 [ 1  3  6 10 15 21 28 36 45]


## Fetching an item from array 

In [25]:
print("4th item of arr1 : ",arr1.item(4))
print("Element of arr2 at row 1 column 2 : ",arr2.item(1,2))

4th item of arr1 :  5
Element of arr2 at row 1 column 2 :  6


## Checking shape of an array

In [33]:
print("Shape of the array arr1 : ",arr1.shape)
print("Shape of the array arr2 : ",arr2.shape)
print("\n")
r,c=arr2.shape
print("row of the array arr2 : ",r)
print("column of the array arr2 : ",c)

Shape of the array arr1 :  (9,)
Shape of the array arr2 :  (3, 3)


row of the array arr2 :  3
column of the array arr2 :  3


## convert ndarray to 1D array

In [37]:
print("converting ndarray to 1D array :",arr2.flatten())

converting ndarray to 1D array : [1 2 3 4 5 6 7 8 9]


## converting 1D array to ndarray

In [43]:
print("converting 1D array to ndarray :\n",arr1.reshape(3,3))

converting 1D array to ndarray :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## sum and product of array

In [44]:
print("Sum of array elements : ",arr1.sum())
print("Product of array elements : ",arr1.prod())

Sum of array elements :  45
Product of array elements :  362880


In [48]:
print(1+2+3+4+5+6+7+8+9)
print(1*2*3*4*5*6*7*8*9)

45
362880


## Max & Min of array element

In [49]:
print("min of array elements : ",arr1.min())
print("max of array elements : ",arr1.max())

min of array elements :  1
max of array elements :  9


## sorting array

In [52]:
print("sort of array elements : ",np.sort(arr1))
print("sort of array elements : ",sorted(arr1))

sort of array elements :  [1 2 3 4 5 6 7 8 9]
sort of array elements :  [1, 2, 3, 4, 5, 6, 7, 8, 9]


## mean ,median ,Varience ,standardDeviation

In [60]:
print("mean of array elements : ",arr1.mean())
print("median of array elements : ",np.median(arr1))
# print("mode of array elements : ",arr1.mode())
print("varience of array elements : ",arr1.var())
print("standard deviation of array elements : ",arr1.std())

mean of array elements :  5.0
median of array elements :  5.0
varience of array elements :  6.666666666666667
standard deviation of array elements :  2.581988897471611


## Array indexing and slicing 

In [72]:
print("arr1 : ",arr1)
print("arr2 : \n",arr2)
print("\nIndexing in array arr1 : ",arr1[0])
print("Indexing in array arr2 : ",arr2[0])
print("second row,two values : ",arr2[1,:2])

arr1 :  [1 2 3 4 5 6 7 8 9]
arr2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Indexing in array arr1 :  1
Indexing in array arr2 :  [1 2 3]
second row,two values :  [4 5]


In [80]:
print(arr2,"\n")
print('Slicing using index')
z=arr2[1:3,1:3] #{row,column} - ranging technique 
print(z)
y=arr2[1:3,[0,2]] #{row,[column numbers]}
print('Slicing using advanced index for column')
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Slicing using index
[[5 6]
 [8 9]]
Slicing using advanced index for column
[[4 6]
 [7 9]]


# WAP to change the value of the following tuple

### (1,2,3,4,6) : change 2 to 200

In [85]:
a=(1,2,3,4,6)
lsta=list(a)
lsta[1]=200
print(tuple(lsta))

(1, 200, 3, 4, 6)


 ## Boolean array indexing 

In [91]:
m=np.array([2,3,4,5,6,7])
n=np.array([5,7,2,8,5,3])

print(m>5)
print(m[m>5])
print(m>n)
print(m[m>n])

[False False False False  True  True]
[6 7]
[False False  True False  True  True]
[4 6 7]


In [102]:
print("number of true value")

print(len(m[m>n]))
print("Alternate method :")
print(list(m>n).count(True))

number of true value
3
Alternate method :
3


## creation of array using command

In [94]:
c=np.array(range(10),int)
print(c,"\n")

[0 1 2 3 4 5 6 7 8 9] 



## creation of array with all ones

In [95]:
print(np.ones((6,7)))

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


## creation of array with all zeros

In [98]:
print(np.zeros((6,7)))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


## creation of array with identiti matrix

In [100]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## linspace

In [112]:
print(np.linspace(2,3,num=5,endpoint=False,retstep=True))

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)


In [121]:
print(np.linspace(2,10,num=5,retstep=True,dtype=int))

(array([ 2,  4,  6,  8, 10]), 2.0)


In [124]:
print(np.full([3,3],10.5,dtype=float))

[[10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]]


# hstack ,vstack ,concatenate

In [146]:
i=np.array([1,2,3,4])
j=np.array([5,6,7,8])

k=np.array([[9,10,11,12],[5,6,7,8]])
l=np.array([[1,2,3,4],[9,10,11,12]])

print("hstack :\n",np.hstack((i,j)))
print("vstack :\n",np.vstack((i,j)))

print("concatenate :\n",np.concatenate(((i,j)),axis=0))

print("concatenate 2D array at axis 0 (vertical) :\n",np.concatenate(((k,l)),axis=0))
print("concatenate 2D array at axis 1 (horizontal):\n",np.concatenate(((k,l)),axis=1))

hstack :
 [1 2 3 4 5 6 7 8]
vstack :
 [[1 2 3 4]
 [5 6 7 8]]
concatenate :
 [1 2 3 4 5 6 7 8]
concatenate 2D array at axis 0 (vertical) :
 [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]
 [ 9 10 11 12]]
concatenate 2D array at axis 1 (horizontal):
 [[ 9 10 11 12  1  2  3  4]
 [ 5  6  7  8  9 10 11 12]]


## Unique values

In [147]:
arr8 = np.array([1,1,2,2,3,3])
arr8uniq =np.unique(arr8)
print("Unique Element values : ",arr8uniq)

arr8uniq,indx=np.unique(arr8, return_index=True)
print("Unique Element values : ",arr8uniq)
print("Unique Element index : ",indx)

arr9 = np.array([1,2,6,4,2,3,2])
arr9uniq,indx = np.unique(arr9,return_inverse=True)
print("Unique Element values : ",arr9uniq)
print("Actual Element index : ",indx)
print("Reconstruct array : ",arr9uniq[indx])

Unique Element values :  [1 2 3]
Unique Element values :  [1 2 3]
Unique Element index :  [0 2 4]
Unique Element values :  [1 2 3 4 6]
Actual Element index :  [0 1 4 3 1 2 1]
Reconstruct array :  [1 2 6 4 2 3 2]


## create an array first

[[1,2,3,4],[9,5,2,4],[9,3,5,6],[3,6,2,3]]

1. Replace the following subset with all 1 : [[5,2], [3,5]]
2. Find the sum of 3rd colum
3. Replace all ODD numbers with -1